import type { SettingsSection } from '../types'

export const SECTION_KEYS: Record<SettingsSection, string[]> = {
  general: [
    'site.name',
    'site.description',
    'site.url',
    'site.admin_email',
    'site.timezone',
    'site.language',
    'site.date_format',
  ],
  appearance: [
    'appearance.logo',
    'appearance.favicon',
    'appearance.primary_color',
    'appearance.accent_color',
    'appearance.border_radius',
    'appearance.font_family',
  ],
  seo: [
    'seo.meta_title_template',
    'seo.meta_description',
    'seo.meta_keywords',
    'seo.og_image',
    'seo.robots_txt',
    'seo.sitemap_enabled',
  ],
  social: [
    'social.facebook',
    'social.twitter',
    'social.instagram',
    'social.linkedin',
    'social.youtube',
    'social.github',
  ],
  navigation: ['navigation.header', 'navigation.footer'],
  comments: [
    'comments.enabled',
    'comments.require_approval',
    'comments.guest_enabled',
    'comments.spam_protection',
    'comments.moderation_level',
    'comments.akismet_key',
    'comments.limit_per_post',
  ],
  users: [],
  integrations: [
    'integrations.ga_id',
    'integrations.gsc_verification',
    'integrations.gtm_id',
    'integrations.turnstile_site_key',
    'integrations.turnstile_secret_key',
    'integrations.smtp_host',
    'integrations.smtp_port',
    'integrations.smtp_username',
    'integrations.smtp_password',
    'integrations.smtp_encryption',
  ],
  security: [
    'security.two_factor_enabled',
    'security.session_timeout',
    'security.password_min_length',
    'security.password_require_special',
  ],
  advanced: [
    'advanced.header_scripts',
    'advanced.footer_scripts',
    'advanced.custom_css',
    'storage.driver',
  ],
}
