import 'css/tailwind.css'

import Header from '@/components/Header'
import SectionContainer from '@/components/SectionContainer'
import Footer from '@/components/Footer'
import siteMetadata from '@/utils/siteMetadata'
import {ThemeProviders} from './theme-providers'
import type {Metadata} from "next";
import { Space_Grotesk } from 'next/font/google'

const space_grotesk = Space_Grotesk({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-space-grotesk',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang={siteMetadata.language}
              className={`${space_grotesk.variable} scroll-smooth`}
              suppressHydrationWarning
        >
        <meta
            name="viewport"
            content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"
        />
        <body className="bg-white text-black antialiased dark:bg-gray-950 dark:text-white">
        <ThemeProviders>
            <SectionContainer>

                <div className="flex h-screen flex-col justify-between font-sans">
                    <Header/>
                    <main className="mb-auto">{children}</main>
                    <Footer/>
                </div>
            </SectionContainer>
        </ThemeProviders>
        </body>
        </html>
    );
}
