name: Turahe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  blog-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.github', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Use Laravel mix to compile asset with Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v2-beta
      with:
        # The Node.js version to configure
          node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run production
    - name: Create Database, Test Migrate and seed database
      run: |
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate --seed --no-interaction -vvv
        php artisan passport:install --force
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit --testdox
